### ISSUE TITLE
Access request for Source Data SFTP

### ISSUE THREAD

**Issue by sapneg-bnym** [os-climate/os_c_data_commons#126]
corporate_data_pipeline

**Comment by MichaelTiemannOSC** [comment]
Sorry about that!  You do have write access to the corporate_data_pipeline repository, but SFTP access is something entirely different.  Assigning Mikhail and Humair, who handle extracurricular functionality in our cluster.

**Comment by redmikhail** [comment]
@sapneg-bnym SFTP access is proxy service that allow you to upload files to S3 bucket redhat-osc-physical-landing-647521352890 under **redhat-osc-physicalrisk-upload** folder using sftp protocol . Please let me know if what you want?  
Please note that we are using ssh key authentication and in order to setup account for you I will need your public ssh key . Normally we can use public key that you have setup with github but yours is generated using  ssh-ed25519 codec , unfortunately  AWS service supports only ssh-rsa . You can generate new one using following instructions https://docs.aws.amazon.com/transfer/latest/userguide/key-management.html#sshkeygen that is specific only for sftp transfer and send me public key by email (only public key!!!) . My email is in my Github profile. You can also add it to your github profile and I can retrieve it from there. Please let me know if you have any questions

**Comment by sapneg-bnym** [comment]
@redmikhail  have emailed you the file, also added it to my profile. I want to run/test the machine learning code in corporate data pipeline repo. I was told, and the readme also mentions that the code reads pdf files and machine learning models from s3 bucket/s and also writes back the output there.

**Comment by redmikhail** [comment]
@sapneg-bnym I have created user ID for you on our sftp server in case if you need to upload anything to landing S3 bucket . At the same time if you need to use existing pdf's in your model I believe that pipelines already should have access to the S3 directly . @MichaelTiemannOSC I wonder if you can point Sapna to the documents/examples on how to run corporate_data_pipeline with access to the S3 data bucket

**Comment by sapneg-bnym** [comment]
@redmikhail I would need user specific aws credentials (access key id and secret) in order to run the pipelines

**Comment by HeatherAck** [comment]
Adding @erikerlandson as he has also provided credentials in the past

**Comment by erikerlandson** [comment]
@Shreyanand  @pacospace  does the `pdf_table_extraction` notebook use the trino catalog S3 creds?  I don't see that in the code.

**Comment by sapneg-bnym** [comment]
@erikerlandson it has instructions which ask to update credentials.env file in the repo. Copying the instructions below:

In order to run this notebook, we need credentials to connect with S3 storage to retrieve and store data.

In an automated environment, the credentials can be specified in a pipeline's environment variables or through Openshift secrets.

For running the notebook in automation in an elyra pipeline, the environment variables can be updated in the notebook "Properties" in the pipeline UI or under `"env_vars"` in the `demo2.pipeline yaml` file.

For running the notebook in a local environment, we will define them as environment variables in a `credentials.env` file at the root of the project repository, and load them using dotenv. An example of what the contents of `credentials.env` could look like is shown below

```
# s3 credentials
S3_ENDPOINT=https://s3.us-east-1.amazonaws.com
S3_BUCKET=ocp-odh-os-demo-s3
AWS_ACCESS_KEY_ID=xxx
AWS_SECRET_ACCESS_KEY=xxx
```

**Comment by erikerlandson** [comment]
bucket `ocp-odh-os-demo-s3` is used by the trino db catalog - are the pdf files being stored on that bucket?
cc @Shreyanand
