### ISSUE TITLE
Add kafka topic FX to Trino catalog on OSC-Cluster2

### ISSUE THREAD

**Issue by caldeirav** [os-climate/os_c_data_commons#193]

**Comment by caldeirav** [comment]
We need to setup the Kafka connector to the existing Kafka topic FX in order for Trino to be able to query FX streams. Setup instructions at:
https://trino.io/docs/current/connector/kafka.html
https://trino.io/docs/current/connector/kafka-tutorial.html

@bryonbaker a topic description file will be required for this

**Comment by caldeirav** [comment]
This has been completed and we now have an FX topic with simulated (but realistic) rates being published.

**Comment by bryonbaker** [comment]
@caldeirav - is the topic file still required?
Also, note that the FX topix is on a test stream.

**Comment by caldeirav** [comment]
Yes we still need the topic file for @HumairAK to setup the connector as per above. We can test the Trino config with any topic at this point.

**Comment by bryonbaker** [comment]
@HumairAK - do you need the topic file before you can set up the connector? Or can it be set up and we add the topic file?
Vincent needs this set up for a presentation next week so we need to get a move alone.

**Comment by bryonbaker** [comment]
I have written the kafka schema definition file:
https://github.com/bryonbaker/markets-pricing-service/blob/main/config/trino-schema.json

@HumairAK - can yu please get this all configured asap?

**Comment by HumairAK** [comment]
Please see: https://github.com/operate-first/apps/pull/2227 
And advise -- thanks.

**Comment by bryonbaker** [comment]
@HumairAK - thanks very much. I think there is one thing left. There is a json file that needs to be mounted in trino. I had the link above to the file above. I have converted that to a config map (see below). That needs to be mounted at the correct place for Trino to find.

The documentation indicates that we need a property to describe where the table definition files are: https://trino.io/docs/current/connector/kafka.html#table-definition-files

The config map we want loaded is:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-schema
data:
  trino-schema.json: |-
    {
        "tableName": "FX",
        "schemaName": "tpch",
        "topicName": "tpch.FX",
        "key": {
            "dataFormat": "json",
            "fields": [
                {
                    "name": "currency",
                    "type": "VARCHAR",
                    "hidden": "false"
                },
                {
                    "name": "base_currency",
                    "type": "VARCHAR",
                    "hidden": "false"
                }
            ]
        },
        "message": {
            "dataFormat" :"json",
            "fields" : [
                {
                    "name": "currency",
                    "mapping": "currency",
                    "type": "VARCHAR"
                },
                {
                    "name": "base_currency",
                    "mapping": "base_currency",
                    "type": "VARCHAR"
                },
                {
                    "name": "ask",
                    "mapping": "ask",
                    "type": "DOUBLE"
                },
                {
                    "name": "bid",
                    "mapping": "bid",
                    "type": "DOUBLE"
                },
                {
                    "name": "date",
                    "mapping": "date",
                    "type": "TIMESTAMP",
                    "dataFormat" :"custom-date-time",
                    "formatHint" : "E M d HH:mm:ss z yyyy"
                },
                {
                    "name": "   high_ask",
                    "mapping": "high_ask",
                    "type": "DOUBLE"
                },
                {
                    "name": "high_bid",
                    "mapping": "high_bid",
                    "type": "DOUBLE"
                },
                {
                    "name": "low_ask",
                    "mapping": "low_ask",
                    "type": "DOUBLE"
                },
                {
                    "name": "low_bid",
                    "mapping": "low_bid",
                    "type": "DOUBLE"
                },
                {
                    "name": "midpoint",
                    "mapping": "midpoint",
                    "type": "DOUBLE"
                }
            ]
        }
    }
```

**Comment by HumairAK** [comment]
the `my-kafka` cluster has been successfully configured with trino, and the table schema has been added. I made some additional changes to the schema to get it working, since `currency` and `base_currency` fields are repeated twice (once in `key` and once in `message` which introduced a column creation conflict. 

The kafka cluster is configured [here](https://github.com/operate-first/apps/blob/master/kfdefs/overlays/osc/osc-cl2/trino/configs/catalogs/kafka_fx.properties). And the table schema is [here](https://github.com/operate-first/apps/blob/master/kfdefs/overlays/osc/osc-cl2/trino/configs/catalogs/kafka_fx.properties)

On the live cluster these can be found [here](https://console-openshift-console.apps.odh-cl2.apps.os-climate.org/k8s/ns/odh-trino/configmaps/trino-catalog) and [here](https://console-openshift-console.apps.odh-cl2.apps.os-climate.org/k8s/ns/odh-trino/configmaps/kafka-table-description-dir) 

As the demos are this week, I have disabled argocd auto sync so you can update the table directly on openshift for the interest of time. Please note that when you update any of these configuration files, **it will trigure a trino reboot.** So anyone using trino may be interrupted.

After the demos I will turn argocd back on, and all changes should be submitted via github pull request.

**Comment by bryonbaker** [comment]
@caldeirav - It has all been set up. Can you give it a test?

@HumairAK - thank you very much!
