### ISSUE TITLE
clean up and rotate leaked credentials

### ISSUE THREAD

**Issue by rynofinn** [os-climate/os_c_data_commons#194]
On Oct 20, 2021 there was a commit to corporate-data-pipeline containing aws credentials to multiple buckets.
As this repo is private, the commit was not immediately scanned and flagged.

Below is the text of a request created in LF Jira for support, but that ticket is not visible to all parties that will be taking action.
Please rotate credentials for account  647521352890

Please rotate keys for the following (the Physical Landing catalog has already been rotated due to a prior accidental commit), so there is no new exposure here):

creds for 'default' catalog
```
DEFAULT_S3_ENDPOINT=https://s3.us-east-1.amazonaws.com
DEFAULT_S3_BUCKET=ocp-odh-os-demo-s3
DEFAULT_ACCESS_KEY=AKIAZ...6OXKV
DEFAULT_SECRET_KEY=Yum6C...+K54IA
```

creds for 'demo1' catalog
```
DEMO1_S3_ENDPOINT=https://s3.us-east-1.amazonaws.com
DEMO1_S3_BUCKET=ocp-odh-data-bucket1-s3
DEMO1_S3_ACCESS_KEY=AKIAZ...DIWD
DEMO1_S3_SECRET_KEY=fiDI12i...HwuJV
```

creds for 'osc physical landing' catalog
```
OSCPL_S3_ENDPOINT=https://s3.us-east-1.amazonaws.com
OSCPL_S3_BUCKET=redhat-osc-physical-landing-647521352890
OSCPL_S3_ACCESS_KEY=AKIAZ...PM6I
OSCPL_S3_SECRET_KEY=wttzb0P...N8lmS
```

trino credentials

```
TRINO_USER=JeremyGohBNP
TRINO_PASSWD=3ab...ee9
TRINO_HOST=trino-secure-odh-trino.apps.odh-cl1.apps.os-climate.org
TRINO_PORT=443
```

I don't know whether the 'demo1' catalog is exposed or not.  I do believe that the Trino access doesn't matter because we now use JWT tokens, not private passwords, but this should be checked.  Would it help to put credentials.env into every .gitignore file?

### Action items: 

- [x] Reach out to stakeholders that the repo in question will be rebased to remove comitted credential information
- [x] Purge credentials for repository history
- [x] Create new keys for these buckets
- [x] Identify services that are using these S3 Buckets
- [x] Switch out creds in identified services with newly created s3 keys

**Comment by MightyNerdEric** [comment]
Edited to remove the link. Github has a habit of caching diff pages like that, so even once it's cleaned up, that page may remain for those with a direct link. I've been through this before; I had to email them directly to have them clean up the cached diff. Shouldn't be an issue since it's a private repo, but lets call it a best practice not to post direct links to the diff containing the credentials anywhere public (or like here, which is still private, but will most likely be public in the future).

**Comment by rynofinn** [comment]
Met with Mikhail to verify my access to AWS account of interest and my access to vault.  However, the secrets that will be rotating are not yet migrated to the vault, so will still be updated in sops.  Humair assistance in identifying the exact secrets to regenerate and where they exist in sops is required.  After that information is available, I should be able to proceed with the rotation process for the list of secrets.

**Comment by redmikhail** [comment]
New keys for ocp-odh-os-demo-s3 and ocp-odh-data-bucket1-s3 have been created and old one deactivated (will be deleted on Monday , Aug 22) .  Openshift objects on both clusters have been updated to use new keys. Key for redhat-osc-physical-landing-647521352890 bucket didn't need to change as affected key has been has been updated in April of 2022 due to unrelated issue

**Comment by redmikhail** [comment]
Incident has been resolved
