### ISSUE TITLE
Remove OSC clusters from ACM as part of operate first migration

### ISSUE THREAD

**Issue by HeatherAck** [os-climate/os_c_data_commons#288]

**Comment by Gregory-Pereira** [comment]
To be specific rather than migrate ACM, it was determined that we are simply removing OSC clusters from infra ACM.  I would like someone to document `kubeadmin` credentials for the three clusters to the new vault instace: https://vault-ui-vault.apps.osc-cl3.eqcq.p1.openshiftapps.com/. This way if the following PR breaks authentication, I can still login to remediate it.  
/cc @redmikhail

**Comment by Gregory-Pereira** [comment]
ACM clusters have been detached and not experiencing any affects to authentication or services. Will reopen if issues arise.
