### ISSUE TITLE
Remind users in setup doc to add the credentials.env to .gitignore

### ISSUE THREAD

**Issue by rmonk-redhat** [os-climate/os_c_data_commons#297]
It may be helpful to add some info in step 4 of https://github.com/os-climate/os_c_data_commons/blob/main/docs/setup-initial-environment.md to remind users to add the credentials.env to .gitignore that way they don't accidentally commit their live credentials to a public repo.

**Comment by MichaelTiemannOSC** [comment]
It would be great to have a pre-commit rule that would also prohibit.  Could somebody write that?  I'm absolute crap when it comes to git, alas.

**Comment by HeatherAck** [comment]
@MightyNerdEric and @ryanaslett - can you please prioritize to add rule and update doc by 5-May? see also: https://jira.linuxfoundation.org/plugins/servlet/desk/portal/2/IT-25442

**Comment by MightyNerdEric** [comment]
I'll update the docs, but the first (and more important) step is to add credentials.env to the .gitignore files in the two template repos. I'll handle that as well; I'll just need reviews on the changes.

**Comment by MightyNerdEric** [comment]
I've opened the following PRs to add credentials.env to the template .gitignore files:
https://github.com/os-climate/data-pipeline-template/pull/1
https://github.com/aicoe-aiops/project-template/pull/59

**Comment by redmikhail** [comment]
Are we still using https://github.com/aicoe-aiops ?

**Comment by HeatherAck** [comment]
@MightyNerdEric will fork aicoe repo and update documentation

**Comment by MightyNerdEric** [comment]
aicoe repo has been forked and the .gitignore updated. I've opened a PR to update the docs with a link to this template, as well as additional info on handling security in credentials.env.

**Comment by MightyNerdEric** [comment]
`credentials.env` has been added to the `.gitignore` file for both template repos, and the docs have been updated.

**Comment by MichaelTiemannOSC** [comment]
This change failed to prevent a credentials.env file from being checked in: https://github.com/os-climate/esg_equivalence/commit/f398daa72b134fc674e47063e84cfe33d2e37714

It was since deleted, but obviously not purged.  Perhaps there's a problem with rogue project templates that, themselves, don't have properly updated .gitignore files.  Every .gitignore on every branch of every repository must be updated across all time, so that no clone of any project can allow credentials.env from being accidentally checked in.

The sooner we can change to a completely different auth mechanism, the better.

@HeatherAck @redmikhail

**Comment by HeatherAck** [comment]
I updated the .gitignore for all the existing repos
