### ISSUE TITLE
Create an Admin Group to administer the Transition Analysis project

### ISSUE THREAD

**Issue by HeatherAck** [os-climate/os_c_data_commons#311]

**Comment by HeatherAck** [comment]
Here is the list of github IDs to have admin privileges for the group, they can then add access for people directly.

sostrades-matthieu-meaux
sostrades-mariemorere
sostrades-pjbarjhoux
sostrades-valentinjoncquieres v
sostrades-dpeltre
sostrades-thierry-chevalier

**Comment by HeatherAck** [comment]
@ryanaslett and @redmikhail can you please set this up for @sostrades-matthieu-meaux

**Comment by MightyNerdEric** [comment]
@HeatherAck (or @sostrades-matthieu-meaux) What resources do they need to have permissions to? I see six repos (5 public, 1 private) that begin with "sostrades". Is it just those repos?

**Comment by MightyNerdEric** [comment]
Also related to the exact scope of the group would be what to name it. "sostrades-admin"? "transition-analysis-admin"? "capgemini-admin" (based on the email that references this issue)?

**Comment by sostrades-pjbarjhoux** [comment]
Hi,

I am at the origin of this demand, so I can provide you some inputs :

We would need a group (sostrades-transition-risk would be fine - it may be a subgroup of the existing transition-risk team) where the above mentionned members have admin rights, (so that we can add new members to this group, for example), in order to manage all these repositories :

sostrades-value-assessment

sostrades-core
sostrades-webgui
sostrades-webapi
sostrades-authapi
witness-core
witness-energy

thanks & Regards
Pierre-Jean

**Comment by MightyNerdEric** [comment]
I've created the group and granted admin permissions to the listed repos.

**Comment by sostrades-pjbarjhoux** [comment]
Thank you @MightyNerdEric @HeatherAck

**Comment by MightyNerdEric** [comment]
@sostrades-pjbarjhoux Whoops, sorry about that oversight. I have changed you all to team maintainers.
