### ISSUE TITLE
OSC-Platform-019: Developer onboarding and data ingestion documentation

### ISSUE THREAD

**Issue by caldeirav** [os-climate/os_c_data_commons#39]
Need a GitHub page showing first steps for a new data scientist using the Data Commons + GitHub environment. Should be based on the structure used in Elyra tutorial and showing:
- How to access structured data using Trino (python client) or CloudBeaver / Superset (visualization)
- How to create persistent data tables / manage data updates with versioning
- How to share the data with another development stream

**Comment by caldeirav** [comment]
Based on the training provided on 17/09, add precisions on the data pipeline flow model in the documentation: 

[10:45 AM] STOECKLE Ludan (Guest)
Trino is the "reference" database? i.e. we should clean input files (from S3 or whatever) using pipelines and store all cleaned data there?


[10:47 AM] Vincent Caldeira (Red Hat) (Guest)
Actually to be specific Trino is used at all stages of data pipeline i.e. ingestion, processing and reference output for analysts.
But we will use different schemas for the various stages because access controls can be managed by catalog / schemas and tables.

[10:48 AM] DELERIS Lea
So that means we load and store back in Trino for all our "main" steps?

[10:48 AM] Vincent Caldeira (Red Hat) (Guest)
Correct

[10:49 AM] STOECKLE Ludan (Guest)
how are separated Dev and Prod trino databases? is there a process to promote our Elyra pipelines in prod?


[10:50 AM] Vincent Caldeira (Red Hat) (Guest)
So right now we think that we will use one catalog per pipeline (for example itr_data_, and we can use different schema for the different sources of data (for examples lseg and urgentem) and then we can use table level for the different stages of processing.
Within Trino we can have dev catalogues and prod catalogues, but we should define the specifics when we start building the pipelines to see what works for you.

Erik Erlandson (Guest) did you mention how teams can bootstrap their pipeline repo (using a template) to get the right structure?
https://github.com/os-climate/os_c_data_commons

**Comment by MichaelTiemannOSC** [comment]
The current documentation flow is pipeline oriented to a fault.  It is certainly helpful to those who live in the pipeline world and want to maintain orientation in that world.  But consider the problem from the perspective of somebody who wants to onboard a dataset (such as the WRI Power Plant data).  Is there anything to do with respect to setting up a "model" (which is presently undocumented--see https://github.com/os-climate/os_c_data_commons/blob/main/docs/setup-initial-environment.md).  Or, given that the data is already in some kind of ingestible format (CSV), should the user skip to the Data Ingestion step fo the DataOps block (also undocumented: https://github.com/os-climate/os_c_data_commons/blob/main/docs/create-ingestion-pipeline.md)?

Suggest we write a user story from the perspective of the WRI data onboarding.  I will make whatever adjustments are needed to the WRI notebook I've created so that it conforms to the guidance of the documentation, including putting the ingestible data where it belongs, renaming the notebook as needed and creating the appropriate virtual environment, etc.  In the end, I expect that ingestion of the WRI data will result in at least three tables: Basic WRI plant data (facts that don't change such as name, lat/lon, fuel type, etc), observed generation (plant_id, year, GWh generated), and estimated generation (plant_id, year, Estimated GWh, notes), and these are the tables that will be exposed as public data via Trino.

**Comment by caldeirav** [comment]
Basic developer documentation including pre-requisities, environment setup and data ingestion pipeline has been published into the developer guide.

https://github.com/os-climate/os_c_data_commons/blob/main/docs/create-ingestion-pipeline.md shows the ingestion flow with code snippets.

Will proceed to close and raise issues for additional doc updates required.
