### ISSUE TITLE
Superset permissions not working for odh-env-user

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [os-climate/os_c_data_commons#78]
When I visit this page:

https://superset-secure-odh-superset.apps.odh-cl1.apps.os-climate.org/superset/welcome/

I use GitHub as my auth mechanism, which takes me to the site, and a chain of access denials.  So I'm clearly missing some sort of authorization use SuperSet.  I have not problems using JupyterHub/Elyra/Trino.

**Comment by HumairAK** [comment]
so just a break down on how this works: 

1. by default anyone that is in the `odh-env-user` can authenticate via ocp
2. anyone that can authenticate via ocp has the `public` superset role see [here](https://superset.apache.org/docs/security#public) for what superset roles do what 
3. anyone in the OCP group named `odh-users` has `admin` superset role. To add someone to this group, append this file [here](https://github.com/operate-first/apps/blob/master/cluster-scope/overlays/prod/osc/osc-cl1/groups/odh-users.yaml)

Now I could just make it so that anyone that can authenticate against ocp has either `alpha`,`gamma`, or `admin` if you guys prefer. Just let me know what works best.

**Comment by erikerlandson** [comment]
I think `alpha` as a default would be good.

**Comment by HumairAK** [comment]
I've made all authenticated users `Alpha` by default. 

@MichaelTiemannOSC can you try to access superset now?

**Comment by MichaelTiemannOSC** [comment]
Sorry to reopen.  While I can now open SuperSet and get to the main landing page without access errors (I am now a member of both Public and Alpha), I see very limited views of data I know is in trino.  When I select the wri_gppd schema, I see only the annual_gwh table, not also the plants and estimated_gwh tables.  There are many other things that seem broken due to insufficent permissions or perhaps the access I expect to see from interacting with trino via notebooks vs. interacting via SuperSet.  So, while I can access SuperSet, it's definitely not yet in a fully working state.

**Comment by MichaelTiemannOSC** [comment]
I don't think I need admin role.  I think something is whacky, either with the data layer or with superset.  With whom should I share my screen when I get a free minute between meetings today?

**Comment by HumairAK** [comment]
@erikerlandson would it be possible for you to meet with @MichaelTiemannOSC and identify the issues, and what permissions are needed?

**Comment by MichaelTiemannOSC** [comment]
Sounds to me like whenever a database is created a permission grant needs to be made to SuperSet.  Or whenever a user logs into SuperSet, trino needs to be queried as to what databases are present in the system.
